require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserEmailConfirmationsController do

  def mock_user_email_confirmation(stubs={})
    @mock_user_email_confirmation ||= mock_model(UserEmailConfirmation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all user_email_confirmations as @user_email_confirmations" do
      UserEmailConfirmation.stub(:all) { [mock_user_email_confirmation] }
      get :index
      assigns(:user_email_confirmations).should eq([mock_user_email_confirmation])
    end
  end

  describe "GET show" do
    it "assigns the requested user_email_confirmation as @user_email_confirmation" do
      UserEmailConfirmation.stub(:find).with("37") { mock_user_email_confirmation }
      get :show, :id => "37"
      assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
    end
  end

  describe "GET new" do
    it "assigns a new user_email_confirmation as @user_email_confirmation" do
      UserEmailConfirmation.stub(:new) { mock_user_email_confirmation }
      get :new
      assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_email_confirmation as @user_email_confirmation" do
      UserEmailConfirmation.stub(:find).with("37") { mock_user_email_confirmation }
      get :edit, :id => "37"
      assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user_email_confirmation as @user_email_confirmation" do
        UserEmailConfirmation.stub(:new).with({'these' => 'params'}) { mock_user_email_confirmation(:save => true) }
        post :create, :user_email_confirmation => {'these' => 'params'}
        assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
      end

      it "redirects to the created user_email_confirmation" do
        UserEmailConfirmation.stub(:new) { mock_user_email_confirmation(:save => true) }
        post :create, :user_email_confirmation => {}
        response.should redirect_to(user_email_confirmation_url(mock_user_email_confirmation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_email_confirmation as @user_email_confirmation" do
        UserEmailConfirmation.stub(:new).with({'these' => 'params'}) { mock_user_email_confirmation(:save => false) }
        post :create, :user_email_confirmation => {'these' => 'params'}
        assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
      end

      it "re-renders the 'new' template" do
        UserEmailConfirmation.stub(:new) { mock_user_email_confirmation(:save => false) }
        post :create, :user_email_confirmation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_email_confirmation" do
        UserEmailConfirmation.stub(:find).with("37") { mock_user_email_confirmation }
        mock_user_email_confirmation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :user_email_confirmation => {'these' => 'params'}
      end

      it "assigns the requested user_email_confirmation as @user_email_confirmation" do
        UserEmailConfirmation.stub(:find) { mock_user_email_confirmation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
      end

      it "redirects to the user_email_confirmation" do
        UserEmailConfirmation.stub(:find) { mock_user_email_confirmation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(user_email_confirmation_url(mock_user_email_confirmation))
      end
    end

    describe "with invalid params" do
      it "assigns the user_email_confirmation as @user_email_confirmation" do
        UserEmailConfirmation.stub(:find) { mock_user_email_confirmation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:user_email_confirmation).should be(mock_user_email_confirmation)
      end

      it "re-renders the 'edit' template" do
        UserEmailConfirmation.stub(:find) { mock_user_email_confirmation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_email_confirmation" do
      UserEmailConfirmation.stub(:find).with("37") { mock_user_email_confirmation }
      mock_user_email_confirmation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the user_email_confirmations list" do
      UserEmailConfirmation.stub(:find) { mock_user_email_confirmation }
      delete :destroy, :id => "1"
      response.should redirect_to(user_email_confirmations_url)
    end
  end

end
